### ISSUE TITLE
有计划提供一个 `对象访问 URL` API 吗？

### ISSUE THREAD

**Issue by tao-zhi-1992** [TencentCloud/cos-sdk-flutter-plugin#1]
如题

**Comment by jordanqin** [comment]
@cj0x39e CosService中现在就有getObjectUrl方法，不过这个方法获取的是未签名的url。你是想要生成带签名的对象url吗？还有没有其他需求，我这边整理一下 进行排期

**Comment by cj0x39e** [comment]
> 

带签名的，目前自己实现了一个，不过这个应该比较常用，可以考虑加下

**Comment by tao-zhi-1992** [comment]
> @cj0x39e CosService中现在就有getObjectUrl方法，不过这个方法获取的是未签名的url。你是想要生成带签名的对象url吗？还有没有其他需求，我这边整理一下 进行排期

带签名的，目前自己实现了一个，不过这个应该比较常用，可以考虑加下

**Comment by jordanqin** [comment]
@cj0x39e  好的，我们下个版本加上这个方法

**Comment by jordanqin** [comment]
@cj0x39e  1.02已发布 提供了getPresignedUrl 下载对象预签名方法，详细使用文档下周会发布到官网

**Comment by tao-zhi-1992** [comment]
> @cj0x39e 1.02已发布 提供了getPresignedUrl 下载对象预签名方法，详细使用文档下周会发布到官网

好的👍🏻
