### ISSUE TITLE
下载任务，ios切换其他应用，无法保持后台继续下载

### ISSUE THREAD

**Issue by mcu13321** [TencentCloud/cos-sdk-flutter-plugin#10]
transferManager.download方法进行任务下载，app切换到其他应用，再返回下载界面，progressCallBack的complete参数置为0，多次操作后，stateCallback的state参数为failed，并且无法通过resume继续任务，只能杀掉app重新启动

**Comment by jordanqin** [comment]
@mcu13321 后台下载需要业务层按照iOS的机制自行实现，或者没有后台下载的需求的话 建议程序切到后台后对下载task进行cancel，回到前台后再重新开始。
