### ISSUE TITLE
PlatformException(channel-error, Unable to establish connection on channel., null, null)

### ISSUE THREAD

**Issue by ColaQian** [TencentCloud/cos-sdk-flutter-plugin#11]
<img width="1191" alt="image" src="https://github.com/TencentCloud/cos-sdk-flutter-plugin/assets/16414132/bfc4b3a8-96ed-490f-b918-ef0b09f1b9e2">
<img width="585" alt="image" src="https://github.com/TencentCloud/cos-sdk-flutter-plugin/assets/16414132/27a80b11-cbd5-4e2e-a0cb-727ede8fe61a">
<img width="767" alt="image" src="https://github.com/TencentCloud/cos-sdk-flutter-plugin/assets/16414132/c7fcf95f-36ef-4953-b9ae-8a07e59edb26">

按照官方的示例initWithSessionCredential  ，但是报了这个问题，请问这是啥原因呢？我这里看着fetchSessionCredentials  都没被调用，flutter 版本3.18.0.
跪求大佬解惑😭。

**Comment by ColaQian** [comment]
tencentcloud_cos_sdk_plugin 安装的是最新 的 1.1.0 版本
<img width="400" alt="image" src="https://github.com/TencentCloud/cos-sdk-flutter-plugin/assets/16414132/c6961666-8bac-46c4-8e1f-9cae63302d7c">

**Comment by jordanqin** [comment]
@ColaQian  我这边用sdk的demo测试了，没问题的。您那边也可以用https://github.com/TencentCloud/cos-sdk-flutter-plugin/tree/main/example先运行看看
