### ISSUE TITLE
ios sdk 6.4.1编译失败

### ISSUE THREAD

**Issue by wh19990906** [TencentCloud/cos-sdk-flutter-plugin#16]
![image](https://github.com/TencentCloud/cos-sdk-flutter-plugin/assets/37242815/dcaefba0-cf62-4280-832f-ff4cee3d645f)

![image](https://github.com/TencentCloud/cos-sdk-flutter-plugin/assets/37242815/088c870d-2400-4337-b55f-f702dcdad979)

qcloud_sdk_ios 6.4.1 中移除了expires，导致编译报错，插件什么时候更新

**Comment by wh19990906** [comment]
![image](https://github.com/TencentCloud/cos-sdk-flutter-plugin/assets/37242815/051e4338-15fb-45c4-87c8-474e2894716b)
6.4.0 中还有expires

![image](https://github.com/TencentCloud/cos-sdk-flutter-plugin/assets/37242815/7c2563f6-ddad-4e5b-bd6b-01af52fffcda)
6.4.1中expires被移除


![image](https://github.com/TencentCloud/cos-sdk-flutter-plugin/assets/37242815/3a0421fa-0057-49ea-943e-2482be2988b7)
tencnetcloud_cos_sdk_plugin.podspec 使用的最新的6.4.1，导致编译报错

**Comment by toknT** [comment]
+1 先fork份固定到6.4.0吧

**Comment by error-code** [comment]
+1

**Comment by wangbo1185742894** [comment]
已修复，麻烦将flutter sdk升级到最新版本
