### ISSUE TITLE
需要升级 QCloudCOSXML 依赖版本，1.1.4 IOS 非 Debug 模式编译后启动 Crash

### ISSUE THREAD

**Issue by tao-zhi-1992** [TencentCloud/cos-sdk-flutter-plugin#17]
instruments 捕获的错误：
```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString count]: unrecognized selector sent to instance 0x303911280'
```

Xcode: Version 15.4
Flutter: 3.19.6
cos-sdk-flutter-plugin: 1.1.4

手动修改 `tencentcloud_cos_sdk_plugin.podspec` 中 `QCloudCOSXML`  为 `6.4.3` （目前为写死的 6.4.1）可以解决。

**Comment by jordanqin** [comment]
@cj0x39e 请升级到最新版本1.1.7并执行pod更新命令解决问题
