### ISSUE TITLE
从1.1.1升级到1.1.5之后报错，再回退到1.1.1仍旧报错

### ISSUE THREAD

**Issue by mcu13321** [TencentCloud/cos-sdk-flutter-plugin#18]
flutter 3.22.2

1.1.1版本在正式环境正常运行，今天开发环境升级到最新版本1.1.5

iOS下升级到1.1.5报错：
The "dev.flutter.pigeon.FlutterCosApi.fetchSessionCredentials' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages muust be sent on the platform thread. Failure to do so may result in data loss or crashes, and mustbe fixed in the plugin or application code creating that channel.

The '"dev.flutter.pigeon.FlutterCosApi.stateCallback'channel sent a message from native to Flutter on a non-platform
thread. Platform channel messages must be sent orn the platform thread. Failure to do so may resulIt in data loss or crashes, and must be fixed inthe plugin or application code creating that channel.

The 'dev.flutter.pigeon.FlutterCosApi.resultFailCallback' channel sent a message from native to Flutter on a non-platform
thread. Platform channel messages must be sent onthe platform thread. Failure to do so may resultt in data loss or crashes, and must be fixed in the plugin or application code creating that channel.

升级到1.1.5再回退到1.1.1之后报相同的错

更正：升级到1.1.5回退到1.1.1报错是因为iOS的包没有回退，需先cache clean清除干净，3.22.2 和1.1.1搭配没问题
1.1.5和3.22.2/3.24.1均有问题，3.24.1搭配1.11.1报错 `Error: Type 'UnmodifiableUint8ListView' not found.`

**Comment by jordanqin** [comment]
@mcu13321 请升级到最新版本1.1.7，参考example项目

**Comment by ThinkCats** [comment]
同样的报错，已经使用了最新的版本了，1.2.0。 在ios上一直报：  The ‘xxxx' channel sent a message from native to Flutter on a non-platform
thread. Platform channel messages must be sent onthe platform thread. Failure to do so may resultt in data loss or crashes, and must be fixed in the plugin or application code creating that channel.

**Comment by jordanqin** [comment]
高版本flutter日志中确实会有线程错误的信息，不过目前看不影响使用，可以先忽略。
应该是高版本的flutter对线程这块要求更严格，sdk需要适配下，我们后续排期解决该问题。
