### ISSUE TITLE
Added gradle namespace

### ISSUE THREAD

**Issue by DizzyDuan** [TencentCloud/cos-sdk-flutter-plugin#19]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':tencentcloud_cos_sdk_plugin'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

     If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

**Comment by jordanqin** [comment]
@DizzyDuan 请测试我们提供的example项目有没有问题，我们这边测试是OK的，或者参考这个自行处理https://stackoverflow.com/questions/76300671/android-getting-error-namespace-not-specified

**Comment by DizzyDuan** [comment]
Testing this problem is very simple. You only need to update the Android Gradle Plugin to 8.x.x to make this problem occur.

Android Studio Koala Feature Drop | 2024.1.2
The default project version created by Flutter 3.24.3 uses Android Gradle Plugin version 8.x.x

Android Gradle Plugin 8.0.0 (April 2023)
Breaking change: namespace required in module-level build script
https://developer.android.com/build/releases/past-releases/agp-8-0-0-release-notes

@jordanqin
