### ISSUE TITLE
在安卓设备上  flutter build apk 报错

### ISSUE THREAD

**Issue by 0FengQiang0** [TencentCloud/cos-sdk-flutter-plugin#4]
在安卓设备上  flutter build apk 报错
tencentcloud_cos_sdk_plugin: ^1.0.4

fengqiang@fengqiangdeMacBook-Pro-2 android % flutter build apk
Changing current working directory to: /Users/fengqiang/Desktop/code/flutter/Nota/nota

💪 Building with sound null safety 💪

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/Users/fengqiang/.pub-cache/hosted/pub.flutter-io.cn/tencentcloud_cos_sdk_plugin-1.0.4/android/build.gradle' line: 19

* What went wrong:
A problem occurred evaluating project ':tencentcloud_cos_sdk_plugin'.
> Basedir /Users/fengqiang/.pub-cache/hosted/pub.flutter-io.cn/app_tracking_transparency-2.0.4/android does not exist

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* Where:
Script '/Users/fengqiang/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 407

* What went wrong:
A problem occurred configuring project ':tencentcloud_cos_sdk_plugin'.
> Failed to notify project evaluation listener.
   > Could not get unknown property 'android' for project ':tencentcloud_cos_sdk_plugin' of type org.gradle.api.Project.
   > Could not get unknown property 'android' for project ':tencentcloud_cos_sdk_plugin' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
Running Gradle task 'assembleRelease'...                            8.4s
Gradle task assembleRelease failed with exit code 1
fengqiang@fengqiangdeMacBook-Pro-2 android %

**Comment by jordanqin** [comment]
麻烦更新下最新版本，如果还是有问题，麻烦说明下本地编译的环以及flutter版本等
