### ISSUE TITLE
flutter 引入1.0.4 iOS运行失败 相关类没有uploadId

### ISSUE THREAD

**Issue by Bingbing0311** [TencentCloud/cos-sdk-flutter-plugin#5]
<img width="1006" alt="image" src="https://github.com/TencentCloud/cos-sdk-flutter-plugin/assets/13670665/42a39f43-c7e4-48d2-a698-cc81d08d7e67">

**Comment by liyangyang6662** [comment]
me too

**Comment by 2803404074** [comment]
请问找到解决方法了吗

**Comment by ohmydragon** [comment]
我们这边有两个 m1 的 mac pro 没有这个问题，但 intel 的一台电脑出现了这个问题，也还没找到解决方案

**Comment by PlacidoLv** [comment]
同样遇到

**Comment by PlacidoLv** [comment]
> 同样遇到

m2p芯片

**Comment by jordanqin** [comment]
@Bingbing0311 @PlacidoLv @2803404074 @liyangyang6662 @ohmydragon 
由于iOS SDK发布新版本删掉了uploadid字段，flutter依赖新版iOS sdk时会出现上述问题。
已经发布了  flutter sdk 1.0.5版本，修复iOS新版本依赖uploadid字段缺失问题。
麻烦各位更新下sdk版本，感谢感谢
