### ISSUE TITLE
在未设置host参数的情况下，Android可以上传成功，iOS提示无法解析域名服务器

### ISSUE THREAD

**Issue by 9527001** [TencentCloud/cos-sdk-flutter-plugin#9]
ios这边确实没有对此处理

![image](https://github.com/TencentCloud/cos-sdk-flutter-plugin/assets/16686832/d655773a-f9dd-4a0b-a067-62046400003d)

**Comment by jordanqin** [comment]
Android和iOS双端host都不是必须配置的，自定义域名的时候才需要，sdk带的示例中默认也是没有设置host的，可以参考下https://github.com/TencentCloud/cos-sdk-flutter-plugin/tree/main/example
